### ISSUE TITLE
Editor in Space Cannot Delete Tag on Dataset

### ISSUE THREAD

**Issue by tcnichol** [clowder-framework/clowder#143]
The editor of a space cannot delete tags on datasets contained within that space.

**To Reproduce**
1. User A: Create space, add dataset to that space, and add a tag.
2. Add User B to space as editor.
3. User B: Delete tag, then refresh page.
4. User B: After refresh, tag re-appears. 

Add and delete tag are listed as permissions for the Editor Role, so this is definitely a bug.

**Comment by tcnichol** [comment]
Could use some feedback about whether this is intended performance or not. 

It looks like the removeTags method in api.Datasets is written so that only the user who added a tag can remove the tag. This occurs after checking the DeleteTag permission where a check is made whether the current user is the user who added the tag. 

If that is how it should work, then it might make sense that the 'delete x' would only appear on tags added by the current user, so it's clear they can't delete other tags. 

Either fix should be relatively easy, just wanted to ask.

**Comment by tcnichol** [comment]
finished. merged

**Comment by robkooper** [comment]
future, if you add to the commit or PR that `fixes #XYZ` the issue will be closed when the PR is merged.
