### ISSUE TITLE
spaces created by api do not show up

### ISSUE THREAD

**Issue by tcnichol** [clowder-framework/clowder#179]
If the user creates a space using the POST api route, the space exists but the following happens:

1. The space is not returned with the GET request
2. The space is not visible under the 'my spaces' tab
3. The space will be under the dropdown for 'explore' or 'you' 
4. After the user clicks on the space, it will show up with the GET request and the 'my spaces' tab.

To replicate, create a space using the api (postman or CURL works) and check under the 'my spaces' tab and with the GET request and the space is created, but is not visible.

**Comment by cpudney** [comment]
Confirmed fixed in 1.16 - thanks.
