### ISSUE TITLE
Endpoint /api/files/bulkRemove returns success even if some files were not deleted because of permissions

### ISSUE THREAD

**Issue by lmarini** [clowder-framework/clowder#209]
The endpoint properly respects permissions and does not delete files that it doesn't have permission to delete, but it returns status:success even if some files were not deleted. It might be better to return a list of files that were deleted a list of files that were not deleted.

https://github.com/clowder-framework/clowder/pull/153/files

**Comment by tcnichol** [comment]
@lmarini 

I can fix this.
In addition to 1. files deleted 2. files not deleted I might also include 3. file ids not found.
