### ISSUE TITLE
return folder as part of file metadata

### ISSUE THREAD

**Issue by robkooper** [clowder-framework/clowder#228]
When returning the file information besides the name, etc, we should return the folder it is in the dataset.

**Comment by MBcode** [comment]
looking folder/file  for metadata [*](http://141.142.218.86/clowder/228.txt)

**Comment by MBcode** [comment]
jsonfFile    additions:
val allPaths: List[List[String]] =  (for (folder <- foldersContainingFile) yield (folderPath(folder, List()).tail))
"path" -> allPaths.map(xl => "/" + xl.map(x => x.toString()).mkString("/")).mkString("")
output: "path": "/folder-1/folder-2",    ;just drop the trailing comma, if only 1 path?

**Comment by MBcode** [comment]
api.Files jsonfile, adds to fields "downloads" and "views"
added to CHANGELOG.md
Will create a new issue, to turn above toString() fields into int, along with "size" which in now also a string
