### ISSUE TITLE
Extraction message start Date should not be an Option

### ISSUE THREAD

**Issue by bodom0015** [clowder-framework/clowder#28]
**Is your feature request related to a problem? Please describe.**
The `start` field should not be optional, since we always know the time that a message came through. Furthermore, having `start` as an `Option[Date]` makes it difficult to sort the resulting extraction lists by Date, as the built-in helpers (e.g. `.sortWith(_.after(_))`) no longer apply.

**Describe the solution you'd like**
`start` should be a `Date` instead of an `Option[Date]`

**Describe alternatives you've considered**
`.sortWith(_.getOrElse(epochDate).after(_.getOrElse(epochDate)))` might work, but is a bit lengthy and potentially error-prone

**Additional context**
The context here was for updating the File/Dataset "Extractions" tab to display a Job ID. Some sorting was necessary to reorder things by Date. We might also consider getting rid of the `end` Date, since it is widely unused.

See https://github.com/clowder-framework/clowder/blob/develop/app/models/Extraction.scala

**Comment by robkooper** [comment]
I think we can also safely drop the end time, I don't believe anybody is using it. I'm in favor of just renaming t from start, time timestamp.
