### ISSUE TITLE
error `Not all dataset IDs found for bulk get request` in logs

### ISSUE THREAD

**Issue by robkooper** [clowder-framework/clowder#295]
**Describe the bug**

It is unclear what the error: `Not all dataset IDs found for bulk get request` means, and I don't believe there is enough information to correctly work with this error message. It would be good to print a list of dataset ids it can not find.

**Comment by MBcode** [comment]
I differentiated the Logger.error being for a [Dataset] or [Folder] 

and add the list of missing IDs
Logger.error("notfound=" + notFound.toString)

to my: not-all-dataset-IDs-found branch

then forced notFound to have some values to see the new Logger.errors:

2022-07-19 13:28:32,531 - [ERROR  ] - application - Not all dataset IDs found for [Folder] bulk get request
2022-07-19 13:28:32,532 - [ERROR  ] - application - notfound=List(62d1daaa1a124a070ed356d9)
Not all dataset IDs found for [Folder] bulk get request
notfound=List(62d1daaa1a124a070ed356d9)
resetting notfound from:List()
to:List(62d1daaa1a124a070ed356d9)
2022-07-19 13:28:32,535 - [ERROR  ] - application - Not all dataset IDs found for [Folder] bulk get request
2022-07-19 13:28:32,536 - [ERROR  ] - application - notfound=List(62d1daaa1a124a070ed356d9)

**Comment by MBcode** [comment]
In [PR368](https://github.com/clowder-framework/clowder/pull/368) that was held up w/a CI bug that didn't have credentials for a github action to upload something for the mongodb container, but should be ok now

**Comment by MBcode** [comment]
This got merged, so I'm closing the issue
