### ISSUE TITLE
Removing users

### ISSUE THREAD

**Issue by ocaisa** [clowder-framework/clowder#3]
Is it possible to delete users? I can make people inactive but there's doesn't seem to be a way to remove them completely.

I'm asking because an (inactive) account is automatically created when someone uses the `Sign up` link, I'd like to able to remove accounts for requests that we refuse.

**Comment by robkooper** [comment]
Yes, however not easy. Biggest problem is what to do if the user has any files or other items associated with their account. 

You can use https://github.com/clowder-framework/clowder/blob/master/scripts/mongodb/migrate_users.py to delete a user and it does some magic to check. Use `migrate_users.py <id>`.

**Comment by ocaisa** [comment]
Ok, thanks, I'll take a look.
