### ISSUE TITLE
error adding dataset to collection

### ISSUE THREAD

**Issue by robkooper** [clowder-framework/clowder#306]
**Describe the bug**
When trying to add a dataset to a collection there is an error:

https://server/api/collections/datasetPossibleParents/undefined?when=550867c9e4b0d15bd2a0d758&date=5

issue probably is the undefined in the url

**To Reproduce**
1. Go to a dataset
2. Click on box to select collection

**Comment by tcnichol** [comment]
I fixed a similar bug for adding dataset to spaces with this pull request:

https://github.com/clowder-framework/clowder/pull/275
