### ISSUE TITLE
same extractor shows up multiple times

### ISSUE THREAD

**Issue by robkooper** [clowder-framework/clowder#327]
**Describe the bug**

When you have multiple instances of clowder running the heartbeat of a new extractor could result into the same extractor being addd multiple times. This seems to be a race condition where we check to see if the extractor exists, and if it does not it will add. With multiple instances of clowder this could result in the same extractor being added multiple times.

**To Reproduce**

1. Make sure extractor does not exist
2. Run multiple clowder instances
3. Start extractor
4. Might show up the same extractor multiple times in extractor list

**Expected behavior**
Extractor should only show once.

**Additional context**
Might need a second process that will check and remove any duplicate instances of the same extractor.

**Comment by robkooper** [comment]
One solution discussed with @ddey2 is the notion of a primary clowder instaance, if we go this route maybe use this for elasticsearch as well.

**Comment by robkooper** [comment]
can probably be tested by setting primary to true/false in custom.conf.

**Comment by ddey2** [comment]
Added the same logical concept for elasticsearch
