### ISSUE TITLE
Include folder name and ID in dataset file lists

### ISSUE THREAD

**Issue by max-zilla** [clowder-framework/clowder#34]
/api/datasets/:id/files will list all files in the dataset as JSON objects, but files within folders have no indication they are not at the root level, making certain operations difficult.

for each file:
```
{
size: "657",
date-created: "Wed Jul 08 10:25:09 CDT 2020",
id: "5f05e555066c371087387c78",
contentType: "text/plain",
filename: "tempnotes.txt"
}
```

I would propose:
```
{
size: "657",
date-created: "Wed Jul 08 10:25:09 CDT 2020",
id: "5f05e555066c371087387c78",
contentType: "text/plain",
filename: "tempnotes.txt",
folder: {
  name: "MyFolder",
  id: "438904901412412412"
}
}
```

**Comment by lbcsept** [comment]
While waiting for this issue to be solved, is there a way to get the folder that contains a specific file, or the reverse : is that possible to get the list of files within a specific folder_id ?

**Comment by tcnichol** [comment]
I created a pull request that I believe fixes this issue.

**Comment by lmarini** [comment]
Thanks @tcnichol !
