### ISSUE TITLE
"Select a collection..." dropdown on dataset returns 400

### ISSUE THREAD

**Issue by max-zilla** [clowder-framework/clowder#343]
https://clowder.ncsa.illinois.edu/clowder/datasets/5e398b4f5e0e2b6b85510821

URL that is called when the dropdown is clicked has incorrect parameter mapping: https://clowder.ncsa.illinois.edu/clowder/api/collections/datasetPossibleParents/undefined?when=5e398b4f5e0e2b6b85510821&date=5

(note that ?when= contains the dataset ID)

**Comment by robkooper** [comment]
I wonder if this is the same as https://github.com/clowder-framework/clowder/pull/307/files#diff-f93c5f084201480bb2e10ed9a303a60ea00553725d1d156dae74ca6e78cffcc5

**Comment by max-zilla** [comment]
https://github.com/clowder-framework/clowder/pull/345
