### ISSUE TITLE
Cannot remove a dataset from a space.

### ISSUE THREAD

**Issue by MWesner3344** [clowder-framework/clowder#349]
**Describe the bug**
The remove button does not work in the Spaces containing the Dataset section of a dataset page. The counter for the number of datasets in the space goes down but the dataset does not get removed from the space.

**To Reproduce**
1. Go to a dataset page where the dataset is contained in a space.
2. Click on the remove button in Spaces containing the Dataset section.
3. Refresh the page.
4. Counter goes down but the dataset remains in the space.

**Expected behavior**
The dataset should be removed from the space.

**Screenshots**
![image](https://user-images.githubusercontent.com/55517825/163417685-ada6d519-a4c2-47b7-a66c-4d15ade0f97a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome

**Comment by tcnichol** [comment]
I am off today but I will be looking into this on Monday.

**Comment by ddey2** [comment]
Hi @robkooper, I investigated the above issue. However, I am not able to reproduce the bug. When I click on Remove, it successfully delete the space and the dataset is no longer within the space.
<img width="1240" alt="Screen Shot 2022-08-02 at 4 06 56 PM" src="https://user-images.githubusercontent.com/22405928/182473769-6e526e7e-fa89-4c19-9975-14aca1432c28.png">
<img width="1253" alt="Screen Shot 2022-08-02 at 4 07 04 PM" src="https://user-images.githubusercontent.com/22405928/182473775-5e9098a0-1f4b-42f7-9807-32378d310cbf.png">

**Comment by ddey2** [comment]
Actually if you go to the space, you can no longer see the dataset.
<img width="1227" alt="Screen Shot 2022-08-02 at 4 10 01 PM" src="https://user-images.githubusercontent.com/22405928/182473980-d1a088f1-960e-4100-8e62-688b642df37a.png">
