### ISSUE TITLE
api/datasets/{id}/downloadFolder endpoint "Cannot parse parameter folderId" when "?key=" query used

### ISSUE THREAD

**Issue by taywll252** [clowder-framework/clowder#356]
**Describe the bug**
I was attempting to use the `api/datasets/{id}/downloadFolder` endpoint. I used the URL path:

`/api/datasets/{id}/downloadFolder?folderId={id}?key={apiKey}`

I received a `"status":"bad request"` and `"message":"Cannot parse parameter folderId"` in return.

The request worked when I opted to use the `X-API-Key` in the `header` instead of the `?key=` query parameter. 

I noticed in the documentation that the `?key=` parameter is deprecated in favor of using the header. However, the message says the `folderId parameter couldn't be parsed`, so something else seems to be going on.

**To Reproduce**
1. Select a `folder ID` and `dataset ID` to download using the `api/datasets/{id}/downloadFolder` endpoint
2. Attempt to execute while using the `?key=` API key query parameter
5. Attempt to execute while **NOT** using the `?key=` query parameter, but the `X-API-Key` header
6. Works as expected

**Expected behavior**
Zip folder of the selected folder ID from the selected dataset ID should be downloaded when using the `?key=` API key query parameter (although deprecated).

**Screenshots**
Example request error:
![clowder_downloadFolder_error](https://user-images.githubusercontent.com/45834109/166513644-71f54403-6dc3-4936-b41f-5ebb4143d358.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Google Chrome Version 100.0.4896.127 (Official Build) (64-bit)

**Additional context**
Clowder Version: 1.20.1#854 branch:master sha1:86ba0e36a38aed057bd5ca104495c5f3af67613a

**Comment by robkooper** [comment]
The url is invalid. The url is made up of the host, path and query string. The query string starts with `?` and each part is separated with `&`. In your example you have two `?` in the query. The correct syntax is: `/api/datasets/{id}/downloadFolder?folderId={id}&key={apiKey}`

**Comment by taywll252** [comment]
@robkooper Thanks for the quick reply. I see that obvious mistake in path syntax now. I was thrown off by the error message pointing to the "folder ID" parameter as the issue and seeing that ?key= is deprecated. Thankfully just an easy fix on my side.
