### ISSUE TITLE
allow to show only spaces you have access to

### ISSUE THREAD

**Issue by robkooper** [clowder-framework/clowder#374]
Right now when you look at the dashboard you can see your spaces and dataets. When you use explore it will show all spaces (including those that you don't have access to) and all datasets/collections that you have access to.

It might be good to explore the spaces you have access to, and make an explicit option to show all the spaces including those you might not have access to.

**Comment by lmarini** [comment]
Another option to consider is to have a special icon or border on the individual spaces in the list that signifies you have accces to it or not.

Maybe also have a filter drop down.

**Comment by robkooper** [comment]
I like the idea of the filter drop down. Main reason is that if I'm on an active server where new spaces are added frequently, this will make the spaces I'm a member of (not owner) disappear and hard to find.

**Comment by ddey2** [comment]
What do you think about the attached screenshot? Will this be clear enough?
<img width="1215" alt="Screen Shot 2022-08-23 at 5 43 52 PM" src="https://user-images.githubusercontent.com/22405928/186279105-b22759cf-afe5-428c-81bb-310562c9840d.png">

**Comment by robkooper** [comment]
Maybe "Joined Spaces" instead of "Other Spaces"?

**Comment by ddey2** [comment]
Yeah, that sounds good. I will then make this dropdown functional. :)
