### ISSUE TITLE
dataset.lastModifiedDate is not updated

### ISSUE THREAD

**Issue by robkooper** [clowder-framework/clowder#386]
**Describe the bug**
When looking at the code and the data, it seems that  lastModifiedDate in the dataset is not updated. I would expect this to be the last time a file was added/removed from the data.

**Comment by ddey2** [comment]
If the metadata for a dataset is changed, we have to update the lastModifiedDate

**Comment by ddey2** [comment]
I created a PR. I just modified the date when a file is added or removed. There are other methods like addFileInfoToZip etc. Do we want to modify the date there as well?

**Comment by ddey2** [comment]
Add the lastModifiedDate to the UI

**Comment by ddey2** [comment]
Adding lastModified date to UI

<img width="1247" alt="Screen Shot 2022-11-16 at 2 56 31 PM" src="https://user-images.githubusercontent.com/22405928/202293092-95296f92-0255-483e-a8aa-be89a1e7a8d7.png">
