### ISSUE TITLE
Extractors appear on the "Submit file for extraction" page after being disabled.

### ISSUE THREAD

**Issue by MWesner3344** [clowder-framework/clowder#387]
**Describe the bug**
Extractors still show up on the "Submit file for extraction" page after being disabled. The "Enabled" box is unchecked but the extractors appear as available to submit a file for extraction. 

**To Reproduce**
1. Disable an extractor on the Extractors page.
2. Go to a file and click on the "Submit file for extraction" button.
3. The disabled extractors are still on this page and have the "Submit" button activated.

**Expected behavior**
The disabled extractor should be removed from the "Submit file for extraction" page or the "Submit" button should be grayed out.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Clowder Version: 1.20.2

**Comment by lmarini** [comment]
@ddey2 can you try to reproduce? Thank you.

**Comment by ddey2** [comment]
I am looking into this. I ll keep you posted.

**Comment by ddey2** [comment]
I have reproduced the issue. It looks like disabling the extractor doesn't remove the extractor from the list of available extractors.  I will address this soon.

**Comment by robkooper** [comment]
Hi @MWesner3344 the ability to enable/disable extractors is not for making them visible and runnable, but have them automatically run when new data is uploaded. So I believe right now it is working as intended.

We are working however on the code to make an extractor private, such that only a specific user can use it, see #300. We hope to soon be able to merge this, enabling the ability to have extractors that are hidden from others.
